version: '3'

services:
  app:
    build:
       context: ./
       dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    working_dir: /go/src/github.com/krdhrk10
    command: tail -f /dev/null
    volumes:
      - ./src:/go/src/github.com/krdhrk10
    depends_on:
      - database

  database:
    image: postgres:11.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - ./mnt/database:/var/lib/postgresql
