version: '3'

services:
  app:
    build:
       context: ./
       dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    working_dir: /go/src/github.com/krdhrk10
    command: tail -f /dev/null
    volumes:
      - ./src:/go/src/github.com/krdhrk10
